language: csharp
solution: iCalWebApp.sln
before_install:
  - sudo apt-get install nunit-console
before_script:
  - nuget restore iCalWebApp.sln
script:
  - xbuild /p:Configuration=Release iCalWebApp.sln
after_script:
  - nunit-console ./Application/bin/Core.Tests.dll
notifications:
  hipchat: 0c48e8ed26ddb78e6c1e883c23ee41@Builds