// Generated by IcedCoffeeScript 108.0.9
(function() {
  var curDate, dateInput;

  window.dateChanged = function(selected) {
    return $('input[id="dateTo"]').data("DateTimePicker").minDate(selected.date);
  };

  $(document).ready(dateInput = "input[id='dateFrom']", $(dateInput).val() !== "" ? curDate = $(dateInput).val() : curDate = new moment(), $(dateInput).datetimepicker({
    format: "L LT",
    minDate: curDate
  }).on('dp.change', dateChanged), dateInput = "input[id='dateTo']", $(dateInput).val() !== "" ? curDate = $(dateInput).val() : curDate = new moment(), $(dateInput).datetimepicker({
    format: "L LT",
    minDate: curDate
  }));

}).call(this);
