// Generated by IcedCoffeeScript 108.0.9
(function() {
  var dateInput;

  window.dateChanged = function(selected) {
    var input;
    input = $('input[id="dateTo"]');
    return input.data("DateTimePicker").minDate(selected.date);
  };

  $(document).ready(dateInput = $('input[id="dateFrom"]'), dateInput.datetimepicker({
    format: "DD/MM/YYYY HH:mm",
    minDate: new moment()
  }).on('dp.change', dateChanged), dateInput = $('input[id="dateTo"]'), dateInput.datetimepicker({
    format: "DD/MM/YYYY HH:mm",
    minDate: new moment()
  }));

}).call(this);
