// Generated by IcedCoffeeScript 108.0.11
(function() {
  window.showModal = function(e) {
    $('.modal-content.modal-upload').show();
    debugger;
  };

  window.cancelModal = function() {
    $('.modal-content.modal-upload').hide();
    return $("#upload").click(window.toggleModal);
  };

  window.toggleModal = function(e) {
    if ((window.showUpload != null) && window.showUpload) {
      window.cancelModal();
      return window.showUpload = false;
    } else {
      window.showModal();
      return window.showUpload = true;
    }
  };

}).call(this);
