// Generated by IcedCoffeeScript 108.0.11
(function() {
  window.toggleModal = function(e) {
    if (window.uploadVisible == null) {
      window.uploadVisible = true;
    }
    $('.modal-content.modal-upload').slideToggle();
    if ((window.uploadVisible != null) && window.uploadVisible) {
      $('#upload').val('Cancel uploading');
      window.uploadVisible = false;
    } else {
      $('#upload').val('Upload calendar');
      window.uploadVisible = true;
    }
    console.log("rogalik");
    return false;
  };

}).call(this);
